"""empty message

Revision ID: 72724835d5a5
Revises: 82b5e240cf9e
Create Date: 2019-09-28 13:22:50.018093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72724835d5a5'
down_revision = '82b5e240cf9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
