"""empty message

Revision ID: 82b5e240cf9e
Revises: 
Create Date: 2019-09-09 19:16:59.749504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b5e240cf9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_name')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.String(length=255), nullable=True),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Integer(), server_default='0', nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('harvest_yield', sa.String(length=255), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_harvest',
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvest.id'], ),
    sa.PrimaryKeyConstraint('crop_id', 'harvest_id')
    )
    op.create_table('field_harvest',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvest.id'], ),
    sa.PrimaryKeyConstraint('field_id', 'harvest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_harvest')
    op.drop_table('crop_harvest')
    op.drop_table('harvest')
    op.drop_table('user')
    op.drop_table('map')
    op.drop_table('images')
    op.drop_table('field')
    op.drop_table('crop')
    # ### end Alembic commands ###
